variables:
  VERSION_PREFIX: '1.0.'
  RELEASE_BRANCH_PREFIX: 'releases/release-'

before_script:
  - npm -v

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  script:
    - echo "Compiling the code..."
    - cd "eharbour"
    - npm config set strict-ssl false
    - npm i -g typescript@5.2.2
    - npm i
    - npm run compile
    - echo "Compile complete."
  rules:
    - if: $CI_COMMIT_BRANCH != "develop" && $CI_COMMIT_BRANCH !~ /^releases\/release-[0-9]+$/

unit-test:
  stage: test
  script:
    - echo "Running unit tests... TBD"
    - echo "Tests completed."
  rules:
    - if: $CI_COMMIT_BRANCH != "develop" && $CI_COMMIT_BRANCH !~ /^releases\/release-[0-9]+$/

publish:
  stage: deploy
  script:
    - echo "Deploying application..."
    - cd "eharbour"
    - npm i -g @vscode/vsce
    - vsce package
    - echo "Application successfully deployed."
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /^releases\/release-[0-9]+$/
